name: isort

on: [push, pull_request]

permissions:
  contents: read

jobs:
  isort:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt

      - name: Run isort
        uses: isort/isort-action@v1
        with:
          requirements-files: requirements.txt
          sort-paths: "rootfs/examples"

  slack-notification:
    needs: [isort]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.isort.outputs.status ) && github.ref_name == github.event.repository.default_branch }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.isort.outputs.status }}
